[package]
name = "gauth"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs-next = "2.0.0"
reqwest = "0.12.15"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.0", features = ["rt-multi-thread", "macros", "fs"] }
toml = "0.8.22"
